from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
from rdflib import Graph, Namespace, RDF, RDFS, OWL

SCRIPTS = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPTS))
import graph_reasoning as CLI  # noqa: E402
import reasoner as R  # noqa: E402

EX = Namespace("http://e/")
PRE = "@prefix ex: <http://e/> . @prefix owl: <http://www.w3.org/2002/07/owl#> . @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> . @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"


def g(body: str) -> Graph:
    return Graph().parse(data=PRE + body, format="turtle")


def kb(tmp_path: Path, body: str, domain: str = "demo") -> Path:
    d = tmp_path / "ontology/system/semantic" / domain
    d.mkdir(parents=True)
    (d / (Path(domain).name + ".ttl")).write_text(PRE + body, encoding="utf-8")
    return tmp_path


def test_subclass_is_transitive_and_types_propagate():
    inferred, errors, _ = R.infer(g("ex:A rdfs:subClassOf ex:B . ex:B rdfs:subClassOf ex:C . ex:x a ex:A ."))
    assert errors == []
    assert (EX.A, RDFS.subClassOf, EX.C) in inferred
    assert (EX.x, RDF.type, EX.B) in inferred and (EX.x, RDF.type, EX.C) in inferred


def test_domain_range_inverse_symmetric_transitive():
    inferred, _, _ = R.infer(g("""
        ex:p rdfs:domain ex:D ; rdfs:range ex:Rg . ex:a ex:p ex:b .
        ex:q owl:inverseOf ex:r . ex:a ex:q ex:b .
        ex:s a owl:SymmetricProperty . ex:a ex:s ex:b .
        ex:t a owl:TransitiveProperty . ex:a ex:t ex:b . ex:b ex:t ex:c ."""))
    assert (EX.a, RDF.type, EX.D) in inferred and (EX.b, RDF.type, EX.Rg) in inferred
    assert (EX.b, EX.r, EX.a) in inferred
    assert (EX.b, EX.s, EX.a) in inferred
    assert (EX.a, EX.t, EX.c) in inferred


def test_trivial_triples_are_dropped_unless_kept():
    base = g("ex:A a owl:Class . ex:x a ex:A .")
    clean, _, _ = R.infer(base)
    assert not any(p == RDF.type and o in (OWL.Thing, RDFS.Resource) for _, p, o in clean)
    assert not any(p == OWL.sameAs and s == o for s, p, o in clean)
    kept, _, _ = R.infer(base, keep_trivial=True)
    assert len(kept) > len(clean)


def test_input_graph_is_not_mutated():
    src = g("ex:A rdfs:subClassOf ex:B . ex:B rdfs:subClassOf ex:C .")
    n = len(src)
    R.infer(src)
    assert len(src) == n


def test_disjoint_violation_is_reported_and_not_leaked_into_inferred():
    inferred, errors, _ = R.infer(g("ex:A owl:disjointWith ex:B . ex:x a ex:A, ex:B ."))
    assert any("Disjoint classes" in e and "http://e/x" in e for e in errors)
    assert not list(inferred.subjects(RDF.type, R.ERR.ErrorMessage))


def test_consistent_graph_has_no_errors():
    assert R.infer(g("ex:A owl:disjointWith ex:B . ex:x a ex:A . ex:y a ex:B ."))[1] == []


def test_functional_property_with_different_values_is_inconsistent():
    _, errors, _ = R.infer(g("ex:f a owl:FunctionalProperty . ex:a ex:f ex:b, ex:c . ex:b owl:differentFrom ex:c ."))
    assert errors, "functional property clash with differentFrom must be reported"


def test_categorize_counts_by_kind():
    inferred, _, _ = R.infer(g("ex:A rdfs:subClassOf ex:B . ex:B rdfs:subClassOf ex:C . ex:x a ex:A ."))
    c = R.categorize(inferred)
    assert c["subClassOf"] >= 1 and c["type"] >= 2


def test_asserted_files_skip_shapes_and_inferred(tmp_path):
    root = kb(tmp_path, "ex:A a owl:Class .")
    d = root / "ontology/system/semantic/demo"
    (d / "demo.shapes.ttl").write_text(PRE)
    (d / "demo.inferred.ttl").write_text(PRE)
    assert [p.name for p in R.asserted_files(root, "demo")] == ["demo.ttl"]


def test_write_status_roundtrip_and_staleness(tmp_path):
    root = kb(tmp_path, "ex:A rdfs:subClassOf ex:B . ex:B rdfs:subClassOf ex:C .")
    assert R.status(root, "demo")["state"] == "missing"
    files = R.asserted_files(root, "demo")
    inferred, _, _ = R.infer(R.load_graph(files))
    path = R.write_inferred(root, "demo", inferred, R.source_hash(root, files), files)
    assert path.name == "demo.inferred.ttl" and path.read_text().startswith("# GENERATED by skb-graph-reasoning")
    assert R.status(root, "demo")["state"] == "fresh"
    assert (EX.A, RDFS.subClassOf, EX.C) in Graph().parse(path, format="turtle")
    (root / "ontology/system/semantic/demo/demo.ttl").write_text(PRE + "ex:A rdfs:subClassOf ex:B .")
    assert R.status(root, "demo")["state"] == "stale"


def test_inferred_file_is_not_an_input_next_time(tmp_path):
    root = kb(tmp_path, "ex:A rdfs:subClassOf ex:B . ex:B rdfs:subClassOf ex:C .")
    files = R.asserted_files(root, "demo")
    inferred, _, _ = R.infer(R.load_graph(files))
    R.write_inferred(root, "demo", inferred, R.source_hash(root, files), files)
    assert [p.name for p in R.asserted_files(root, "demo")] == ["demo.ttl"]


def test_query_sees_closure_unless_disabled():
    base = g("ex:A rdfs:subClassOf ex:B . ex:B rdfs:subClassOf ex:C .")
    ask = "PREFIX ex: <http://e/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> ASK { ex:A rdfs:subClassOf ex:C }"
    assert R.query(base, ask).askAnswer is True
    assert R.query(base, ask, with_closure=False).askAnswer is False


def test_cli_reason_apply_check_status_query(tmp_path, capsys):
    root = kb(tmp_path, "ex:A rdfs:subClassOf ex:B . ex:B rdfs:subClassOf ex:C . ex:x a ex:A .")
    base = ["--target", str(root), "--domain", "demo"]
    assert CLI.main(["reason", *base, "--apply", "--no-validate"]) == 0
    assert "inferred=" in capsys.readouterr().out
    assert CLI.main(["status", *base]) == 0
    assert CLI.main(["check", *base]) == 0
    capsys.readouterr()
    assert CLI.main(["query", *base, "--json", "--sparql", "PREFIX ex: <http://e/> SELECT ?c WHERE { ex:x a ?c } ORDER BY ?c"]) == 0
    rows = json.loads(capsys.readouterr().out)["rows"]
    assert {r["c"] for r in rows} >= {"http://e/A", "http://e/B", "http://e/C"}


def test_cli_refuses_to_write_when_inconsistent(tmp_path, capsys):
    root = kb(tmp_path, "ex:A owl:disjointWith ex:B . ex:x a ex:A, ex:B .")
    base = ["--target", str(root), "--domain", "demo"]
    assert CLI.main(["check", *base]) == 1
    assert CLI.main(["reason", *base, "--apply", "--no-validate"]) == 3
    assert not R.inferred_path(root, "demo").exists()
    assert CLI.main(["reason", *base, "--apply", "--no-validate", "--allow-inconsistent"]) == 0
    assert R.inferred_path(root, "demo").exists()


def test_cli_missing_domain_or_files_exit_with_message(tmp_path):
    with pytest.raises(SystemExit):
        CLI.main(["status", "--target", str(tmp_path)])
    with pytest.raises(SystemExit):
        CLI.main(["stats", "--target", str(tmp_path), "--domain", "nope"])


def test_xsd_literal_clash_is_an_artifact_not_an_inconsistency():
    # 같은 어휘형 "1" 이 문자열과 숫자로 함께 쓰이면 owlrl 이 xsd:decimal/xsd:string disjoint 위반을 보고한다
    _, errors, artifacts = R.infer(g('ex:a ex:count 1 . ex:b ex:label "1" .'))
    assert errors == []
    assert R.split_errors(["Disjoint classes http://www.w3.org/2001/XMLSchema#decimal and http://www.w3.org/2001/XMLSchema#string have a common individual 1"])[1]


def test_literal_and_standard_vocabulary_subjects_are_not_inferred():
    inferred, _, _ = R.infer(g('ex:a ex:count 1 . ex:A a owl:Class .'))
    from rdflib import Literal, URIRef
    assert not any(isinstance(s, Literal) for s, _, _ in inferred)
    assert not any(isinstance(s, URIRef) and str(s).startswith("http://www.w3.org/") for s, _, _ in inferred)
    # 파생 TTL 은 직렬화해서 다시 읽을 수 있어야 한다
    Graph().parse(data=inferred.serialize(format="turtle"), format="turtle")


def test_cli_check_ignores_artifacts_unless_strict(tmp_path):
    root = kb(tmp_path, 'ex:a ex:count 1 . ex:b ex:label "1" .')
    base = ["--target", str(root), "--domain", "demo"]
    assert CLI.main(["check", *base]) == 0
